services:
  web:
    build:
      context: "."
      dockerfile: "dev.Dockerfile"
      args:
        - github_username
        - github_password 
        - DB_USERNAME
        - DB_PASSWORD
        - DB_HOST
        - DB_TABLENAME
        - DB_INSTANCE_NAME
    command:
      ["/bin/bash"]
      #["npm", "run", "dev"]
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      DB_HOST: "db"
    links:
      - "db"
    tty: true
  db:
    image: "gcr.io/cloudsql-docker/gce-proxy:1.19.1"
    command:
      ["/cloud_sql_proxy",
       "-instances=new-business-development:asia-northeast1:boaters-app-crawling-stg=tcp:0.0.0.0:5432",
       "-credential_file=/config/application_default_credentials.json"]
    volumes:
      - "$HOME/.config/gcloud:/config"
    ports:
      - "5432:5432"
