services:
  devshell:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: devshell
    working_dir: /workspace
    command: sleep infinity
    volumes:
      - ${HOME}:/workspace
      - ${PWD}/.zshrc:/root/.zshrc:ro
      - ${HOME}/.vimrc:/root/.vimrc:ro
      - ${HOME}/.config/gcloud:/root/.config/gcloud
      - ${HOME}/.kube:/root/.kube
      - gh-config:/root/.config/gh
    environment:
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true

volumes:
  gh-config:
